//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadTai.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PadTai.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discounts.
        /// </summary>
        internal static string Addbtns_btn17 {
            get {
                return ResourceManager.GetString("Addbtns-btn17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dishes.
        /// </summary>
        internal static string Addbtns_btn18 {
            get {
                return ResourceManager.GetString("Addbtns-btn18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tables.
        /// </summary>
        internal static string Addbtns_btn19 {
            get {
                return ResourceManager.GetString("Addbtns-btn19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Calculator.
        /// </summary>
        internal static string Addbtns_btn21 {
            get {
                return ResourceManager.GetString("Addbtns-btn21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients.
        /// </summary>
        internal static string Addbtns_btn22 {
            get {
                return ResourceManager.GetString("Addbtns-btn22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ind-discount.
        /// </summary>
        internal static string Addbtns_btn23 {
            get {
                return ResourceManager.GetString("Addbtns-btn23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancelled.
        /// </summary>
        internal static string Addbtns_btn24 {
            get {
                return ResourceManager.GetString("Addbtns-btn24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Best regards.
        /// </summary>
        internal static string Bestregards {
            get {
                return ResourceManager.GetString("Bestregards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn-Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Btn_close {
            get {
                return ResourceManager.GetString("Btn-close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter.
        /// </summary>
        internal static string Btn_Enter {
            get {
                return ResourceManager.GetString("Btn-Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price split .
        /// </summary>
        internal static string Btn_morebtn18 {
            get {
                return ResourceManager.GetString("Btn-morebtn18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chat.
        /// </summary>
        internal static string Btn_morebtn19 {
            get {
                return ResourceManager.GetString("Btn-morebtn19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hall display.
        /// </summary>
        internal static string Btn_morebtn20 {
            get {
                return ResourceManager.GetString("Btn-morebtn20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Printing style.
        /// </summary>
        internal static string Btn_morebtn21 {
            get {
                return ResourceManager.GetString("Btn-morebtn21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bill split.
        /// </summary>
        internal static string Btn_morebtn22 {
            get {
                return ResourceManager.GetString("Btn-morebtn22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shift cashier.
        /// </summary>
        internal static string Btn_morebtn23 {
            get {
                return ResourceManager.GetString("Btn-morebtn23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kitchen display.
        /// </summary>
        internal static string Btn_morebtn24 {
            get {
                return ResourceManager.GetString("Btn-morebtn24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Btn_save {
            get {
                return ResourceManager.GetString("Btn-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Btnannuler {
            get {
                return ResourceManager.GetString("Btnannuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        internal static string Btnconfirm {
            get {
                return ResourceManager.GetString("Btnconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restricted.
        /// </summary>
        internal static string BTNDIS_btn2 {
            get {
                return ResourceManager.GetString("BTNDIS-btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check and correct your data if necessary, before inserting them.
        /// </summary>
        internal static string Checkdata {
            get {
                return ResourceManager.GetString("Checkdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à §.
        /// </summary>
        internal static string Clavierbtn1 {
            get {
                return ResourceManager.GetString("Clavierbtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ².
        /// </summary>
        internal static string Clavierbtn2 {
            get {
                return ResourceManager.GetString("Clavierbtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ±.
        /// </summary>
        internal static string Clavierbtn3 {
            get {
                return ResourceManager.GetString("Clavierbtn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ∞.
        /// </summary>
        internal static string Clavierbtn4 {
            get {
                return ResourceManager.GetString("Clavierbtn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à º.
        /// </summary>
        internal static string Clavierbtn5 {
            get {
                return ResourceManager.GetString("Clavierbtn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à —.
        /// </summary>
        internal static string Clavierbtn6 {
            get {
                return ResourceManager.GetString("Clavierbtn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à µ.
        /// </summary>
        internal static string Clavierbtn7 {
            get {
                return ResourceManager.GetString("Clavierbtn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        internal static string ClavierbtnA {
            get {
                return ResourceManager.GetString("ClavierbtnA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B.
        /// </summary>
        internal static string ClavierbtnB {
            get {
                return ResourceManager.GetString("ClavierbtnB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C.
        /// </summary>
        internal static string ClavierbtnC {
            get {
                return ResourceManager.GetString("ClavierbtnC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D.
        /// </summary>
        internal static string ClavierbtnD {
            get {
                return ResourceManager.GetString("ClavierbtnD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E.
        /// </summary>
        internal static string ClavierbtnE {
            get {
                return ResourceManager.GetString("ClavierbtnE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à F.
        /// </summary>
        internal static string ClavierbtnF {
            get {
                return ResourceManager.GetString("ClavierbtnF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à G.
        /// </summary>
        internal static string ClavierbtnG {
            get {
                return ResourceManager.GetString("ClavierbtnG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H.
        /// </summary>
        internal static string ClavierbtnH {
            get {
                return ResourceManager.GetString("ClavierbtnH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I.
        /// </summary>
        internal static string ClavierbtnI {
            get {
                return ResourceManager.GetString("ClavierbtnI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J.
        /// </summary>
        internal static string ClavierbtnJ {
            get {
                return ResourceManager.GetString("ClavierbtnJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à K.
        /// </summary>
        internal static string ClavierbtnK {
            get {
                return ResourceManager.GetString("ClavierbtnK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L.
        /// </summary>
        internal static string ClavierbtnL {
            get {
                return ResourceManager.GetString("ClavierbtnL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M.
        /// </summary>
        internal static string ClavierbtnM {
            get {
                return ResourceManager.GetString("ClavierbtnM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N.
        /// </summary>
        internal static string ClavierbtnN {
            get {
                return ResourceManager.GetString("ClavierbtnN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à O.
        /// </summary>
        internal static string ClavierbtnO {
            get {
                return ResourceManager.GetString("ClavierbtnO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à P.
        /// </summary>
        internal static string ClavierbtnP {
            get {
                return ResourceManager.GetString("ClavierbtnP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Q.
        /// </summary>
        internal static string ClavierbtnQ {
            get {
                return ResourceManager.GetString("ClavierbtnQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à R.
        /// </summary>
        internal static string ClavierbtnR {
            get {
                return ResourceManager.GetString("ClavierbtnR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S.
        /// </summary>
        internal static string ClavierbtnS {
            get {
                return ResourceManager.GetString("ClavierbtnS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T.
        /// </summary>
        internal static string ClavierbtnT {
            get {
                return ResourceManager.GetString("ClavierbtnT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à U.
        /// </summary>
        internal static string ClavierbtnU {
            get {
                return ResourceManager.GetString("ClavierbtnU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à V.
        /// </summary>
        internal static string ClavierbtnV {
            get {
                return ResourceManager.GetString("ClavierbtnV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W.
        /// </summary>
        internal static string ClavierbtnW {
            get {
                return ResourceManager.GetString("ClavierbtnW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X.
        /// </summary>
        internal static string ClavierbtnX {
            get {
                return ResourceManager.GetString("ClavierbtnX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y.
        /// </summary>
        internal static string ClavierbtnY {
            get {
                return ResourceManager.GetString("ClavierbtnY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z.
        /// </summary>
        internal static string ClavierbtnZ {
            get {
                return ResourceManager.GetString("ClavierbtnZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Excel file already opened. Close it first!.
        /// </summary>
        internal static string Closefile {
            get {
                return ResourceManager.GetString("Closefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close today&apos;s shift?.
        /// </summary>
        internal static string Closesession {
            get {
                return ResourceManager.GetString("Closesession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coming soon!.
        /// </summary>
        internal static string Comingsoon {
            get {
                return ResourceManager.GetString("Comingsoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payments.
        /// </summary>
        internal static string Dailypay_btn {
            get {
                return ResourceManager.GetString("Dailypay-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prints.
        /// </summary>
        internal static string Dailyprints_btn {
            get {
                return ResourceManager.GetString("Dailyprints-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discount amount.
        /// </summary>
        internal static string Dailyreport_discount {
            get {
                return ResourceManager.GetString("Dailyreport-discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discounted.
        /// </summary>
        internal static string Dailyreport_discounted {
            get {
                return ResourceManager.GetString("Dailyreport-discounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dishes sold.
        /// </summary>
        internal static string Dailyreport_dishes {
            get {
                return ResourceManager.GetString("Dailyreport-dishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dishes names.
        /// </summary>
        internal static string Dailyreport_dname {
            get {
                return ResourceManager.GetString("Dailyreport-dname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dish type.
        /// </summary>
        internal static string Dailyreport_foodtype {
            get {
                return ResourceManager.GetString("Dailyreport-foodtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Receipts.
        /// </summary>
        internal static string Dailyreport_lbl3 {
            get {
                return ResourceManager.GetString("Dailyreport-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Revenue.
        /// </summary>
        internal static string Dailyreport_lbl4 {
            get {
                return ResourceManager.GetString("Dailyreport-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment method.
        /// </summary>
        internal static string Dailyreport_paytype {
            get {
                return ResourceManager.GetString("Dailyreport-paytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery type.
        /// </summary>
        internal static string Dailyreport_place {
            get {
                return ResourceManager.GetString("Dailyreport-place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price.
        /// </summary>
        internal static string Dailyreport_price {
            get {
                return ResourceManager.GetString("Dailyreport-price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity.
        /// </summary>
        internal static string Dailyreport_qte {
            get {
                return ResourceManager.GetString("Dailyreport-qte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receipts content.
        /// </summary>
        internal static string Dailyreport_reccontent {
            get {
                return ResourceManager.GetString("Dailyreport-reccontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rec ID.
        /// </summary>
        internal static string Dailyreport_Recid {
            get {
                return ResourceManager.GetString("Dailyreport-Recid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amount.
        /// </summary>
        internal static string Dailyreport_sum {
            get {
                return ResourceManager.GetString("Dailyreport-sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        internal static string Dailyreport_total {
            get {
                return ResourceManager.GetString("Dailyreport-total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1st work day.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Index error.
        /// </summary>
        internal static string DC_IndError {
            get {
                return ResourceManager.GetString("DC-IndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your business name.
        /// </summary>
        internal static string DC_lbl1 {
            get {
                return ResourceManager.GetString("DC-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email verification code.
        /// </summary>
        internal static string DC_lbl11 {
            get {
                return ResourceManager.GetString("DC-lbl11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        internal static string DC_lbl2 {
            get {
                return ResourceManager.GetString("DC-lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string DC_lbl3 {
            get {
                return ResourceManager.GetString("DC-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Already have an account ?.
        /// </summary>
        internal static string DC_lbl6 {
            get {
                return ResourceManager.GetString("DC-lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à *Business logo ↑.
        /// </summary>
        internal static string DC_lbl7 {
            get {
                return ResourceManager.GetString("DC-lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Email.
        /// </summary>
        internal static string DC_lbl8 {
            get {
                return ResourceManager.GetString("DC-lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Password.
        /// </summary>
        internal static string DC_lbl9 {
            get {
                return ResourceManager.GetString("DC-lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string DC_linkbl1 {
            get {
                return ResourceManager.GetString("DC-linkbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create your account.
        /// </summary>
        internal static string DC_rbtn1 {
            get {
                return ResourceManager.GetString("DC-rbtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        internal static string DC_rbtn2 {
            get {
                return ResourceManager.GetString("DC-rbtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm code.
        /// </summary>
        internal static string DC_rbtn5 {
            get {
                return ResourceManager.GetString("DC-rbtn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send code.
        /// </summary>
        internal static string DC_rbtn6 {
            get {
                return ResourceManager.GetString("DC-rbtn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete account.
        /// </summary>
        internal static string DC_rbtn7 {
            get {
                return ResourceManager.GetString("DC-rbtn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, enter a name first.
        /// </summary>
        internal static string DC_try11 {
            get {
                return ResourceManager.GetString("DC-try11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, enter a password first.
        /// </summary>
        internal static string DC_try12 {
            get {
                return ResourceManager.GetString("DC-try12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, enter your email first.
        /// </summary>
        internal static string DC_try13 {
            get {
                return ResourceManager.GetString("DC-try13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verify your email first.
        /// </summary>
        internal static string DC_try14 {
            get {
                return ResourceManager.GetString("DC-try14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account created successfully.
        /// </summary>
        internal static string DC_try15 {
            get {
                return ResourceManager.GetString("DC-try15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string DC_try16 {
            get {
                return ResourceManager.GetString("DC-try16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error creating account..
        /// </summary>
        internal static string DC_try17 {
            get {
                return ResourceManager.GetString("DC-try17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an account first.
        /// </summary>
        internal static string DC_try18 {
            get {
                return ResourceManager.GetString("DC-try18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation code sent successfully!.
        /// </summary>
        internal static string DC_try19 {
            get {
                return ResourceManager.GetString("DC-try19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send confirmation code.
        /// </summary>
        internal static string DC_try20 {
            get {
                return ResourceManager.GetString("DC-try20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 6 figures expected.
        /// </summary>
        internal static string DC_try21 {
            get {
                return ResourceManager.GetString("DC-try21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation code can&apos;t be null.
        /// </summary>
        internal static string DC_try22 {
            get {
                return ResourceManager.GetString("DC-try22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect Confirmation code.
        /// </summary>
        internal static string DC_try23 {
            get {
                return ResourceManager.GetString("DC-try23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email confirmed successfully.
        /// </summary>
        internal static string DC_try24 {
            get {
                return ResourceManager.GetString("DC-try24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery Pie.
        /// </summary>
        internal static string Dcharts_deliveryt1 {
            get {
                return ResourceManager.GetString("Dcharts-deliveryt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deliveries/Hour.
        /// </summary>
        internal static string Dcharts_deliveryt2 {
            get {
                return ResourceManager.GetString("Dcharts-deliveryt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discounts Pie.
        /// </summary>
        internal static string Dcharts_discountt1 {
            get {
                return ResourceManager.GetString("Dcharts-discountt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discounts/Hour.
        /// </summary>
        internal static string Dcharts_discountt2 {
            get {
                return ResourceManager.GetString("Dcharts-discountt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dish categories pie.
        /// </summary>
        internal static string Dcharts_disht1 {
            get {
                return ResourceManager.GetString("Dcharts-disht1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dish type/Hour.
        /// </summary>
        internal static string Dcharts_disht2 {
            get {
                return ResourceManager.GetString("Dcharts-disht2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payments Pie.
        /// </summary>
        internal static string Dcharts_payt1 {
            get {
                return ResourceManager.GetString("Dcharts-payt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Used payment/Hour.
        /// </summary>
        internal static string Dcharts_payt2 {
            get {
                return ResourceManager.GetString("Dcharts-payt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receipt count/hour.
        /// </summary>
        internal static string Dcharts_receiptt1 {
            get {
                return ResourceManager.GetString("Dcharts-receiptt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receipts frequency.
        /// </summary>
        internal static string Dcharts_receiptt2 {
            get {
                return ResourceManager.GetString("Dcharts-receiptt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account deleted Successfully.
        /// </summary>
        internal static string Del_account {
            get {
                return ResourceManager.GetString("Del-account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this item?.
        /// </summary>
        internal static string Delete_lbl1 {
            get {
                return ResourceManager.GetString("Delete-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No order at the moment.
        /// </summary>
        internal static string DR_lbl3 {
            get {
                return ResourceManager.GetString("DR-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email Confirmation.
        /// </summary>
        internal static string Email_confirm {
            get {
                return ResourceManager.GetString("Email-confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your confirmation code is:.
        /// </summary>
        internal static string Email_conftext {
            get {
                return ResourceManager.GetString("Email-conftext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please do not reply to this email.
        /// </summary>
        internal static string Email_noreply {
            get {
                return ResourceManager.GetString("Email-noreply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonuses.
        /// </summary>
        internal static string EMPTT_bonus {
            get {
                return ResourceManager.GetString("EMPTT-bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Working dates:.
        /// </summary>
        internal static string EMPTT_daysofmonth {
            get {
                return ResourceManager.GetString("EMPTT-daysofmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day team:.
        /// </summary>
        internal static string EMPTT_Empworking {
            get {
                return ResourceManager.GetString("EMPTT-Empworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Final salary.
        /// </summary>
        internal static string EMPTT_finalsalary {
            get {
                return ResourceManager.GetString("EMPTT-finalsalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gross salary.
        /// </summary>
        internal static string EMPTT_grosssalary {
            get {
                return ResourceManager.GetString("EMPTT-grosssalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print timetable.
        /// </summary>
        internal static string EMPTT_lbl4 {
            get {
                return ResourceManager.GetString("EMPTT-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Penalties.
        /// </summary>
        internal static string EMPTT_penalities {
            get {
                return ResourceManager.GetString("EMPTT-penalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salary/ h.
        /// </summary>
        internal static string EMPTT_Salary_h {
            get {
                return ResourceManager.GetString("EMPTT-Salary/h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total hours.
        /// </summary>
        internal static string EMPTT_sumhours {
            get {
                return ResourceManager.GetString("EMPTT-sumhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Working hours.
        /// </summary>
        internal static string EMPTT_workhours {
            get {
                return ResourceManager.GetString("EMPTT-workhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à E-mail cannot be null.
        /// </summary>
        internal static string Empty_email {
            get {
                return ResourceManager.GetString("Empty-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password can&apos;t be null..
        /// </summary>
        internal static string Empty_password {
            get {
                return ResourceManager.GetString("Empty-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error deleting account.
        /// </summary>
        internal static string ERRORDel_account {
            get {
                return ResourceManager.GetString("ERRORDel-account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data to insert. Add data from Excel first.
        /// </summary>
        internal static string Exceldata {
            get {
                return ResourceManager.GetString("Exceldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to insert data..
        /// </summary>
        internal static string Failedinsert {
            get {
                return ResourceManager.GetString("Failedinsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table n°:.
        /// </summary>
        internal static string FCH_Lbl2 {
            get {
                return ResourceManager.GetString("FCH-Lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client name:.
        /// </summary>
        internal static string FCH_lbl9 {
            get {
                return ResourceManager.GetString("FCH-lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string FCK_btn1 {
            get {
                return ResourceManager.GetString("FCK-btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upgrade payment.
        /// </summary>
        internal static string FCK_btn17 {
            get {
                return ResourceManager.GetString("FCK-btn17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Customer discount..
        /// </summary>
        internal static string FCK_btn2 {
            get {
                return ResourceManager.GetString("FCK-btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay.
        /// </summary>
        internal static string FCK_btn3 {
            get {
                return ResourceManager.GetString("FCK-btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery.
        /// </summary>
        internal static string FCK_btn36 {
            get {
                return ResourceManager.GetString("FCK-btn36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discount:.
        /// </summary>
        internal static string FCK_lbl4 {
            get {
                return ResourceManager.GetString("FCK-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay:.
        /// </summary>
        internal static string FCK_lbl5 {
            get {
                return ResourceManager.GetString("FCK-lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   Comment....
        /// </summary>
        internal static string FCK_txt1Watermark {
            get {
                return ResourceManager.GetString("FCK-txt1Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your data must be in the first and the second columns.
        /// </summary>
        internal static string FGI_Colinsert {
            get {
                return ResourceManager.GetString("FGI-Colinsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value(s) in the first column must be integers.
        /// </summary>
        internal static string FGI_Colinteger {
            get {
                return ResourceManager.GetString("FGI-Colinteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;The value(s) in the third column must be integers&quot;.
        /// </summary>
        internal static string FGSI_Intcol3 {
            get {
                return ResourceManager.GetString("FGSI-Intcol3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GROUP(S) OF DISHES.
        /// </summary>
        internal static string FI_lbl4 {
            get {
                return ResourceManager.GetString("FI-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOOD ITEM(S).
        /// </summary>
        internal static string FII_lbl4 {
            get {
                return ResourceManager.GetString("FII-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOOD ITEM TYPE(S).
        /// </summary>
        internal static string FIIT_lbl4 {
            get {
                return ResourceManager.GetString("FIIT-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by gender&quot;.
        /// </summary>
        internal static string Filterbygender {
            get {
                return ResourceManager.GetString("Filterbygender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filter by job.
        /// </summary>
        internal static string Filterbyjob {
            get {
                return ResourceManager.GetString("Filterbyjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à      Delivery type:.
        /// </summary>
        internal static string FIM_delivery {
            get {
                return ResourceManager.GetString("FIM-delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à      Discount (%):.
        /// </summary>
        internal static string FIM_discount {
            get {
                return ResourceManager.GetString("FIM-discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à      Payment method:.
        /// </summary>
        internal static string FIM_paytype {
            get {
                return ResourceManager.GetString("FIM-paytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à      Total amount:.
        /// </summary>
        internal static string FIM_totalprice {
            get {
                return ResourceManager.GetString("FIM-totalprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DISH(ES).
        /// </summary>
        internal static string FIT_lbl4 {
            get {
                return ResourceManager.GetString("FIT-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continious discount calculation.
        /// </summary>
        internal static string FSettings1 {
            get {
                return ResourceManager.GetString("FSettings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show dish picture if any.
        /// </summary>
        internal static string FSettings2 {
            get {
                return ResourceManager.GetString("FSettings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play notifications sound.
        /// </summary>
        internal static string FSettings3 {
            get {
                return ResourceManager.GetString("FSettings3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve draft receipts.
        /// </summary>
        internal static string FSettings4 {
            get {
                return ResourceManager.GetString("FSettings4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use app virtual keyboard.
        /// </summary>
        internal static string FSettings5 {
            get {
                return ResourceManager.GetString("FSettings5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your data must be in the 1st, 2nd, and 3rd columns.
        /// </summary>
        internal static string FSGI_Col123 {
            get {
                return ResourceManager.GetString("FSGI-Col123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOOD SUB GROUP(S).
        /// </summary>
        internal static string FSGI_lbl4 {
            get {
                return ResourceManager.GetString("FSGI-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FOOD SUB SUB GROUP(S).
        /// </summary>
        internal static string FSSGI_lbl4 {
            get {
                return ResourceManager.GetString("FSSGI-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Female.
        /// </summary>
        internal static string GenderF {
            get {
                return ResourceManager.GetString("GenderF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Male.
        /// </summary>
        internal static string GenderH {
            get {
                return ResourceManager.GetString("GenderH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other.
        /// </summary>
        internal static string GenderO {
            get {
                return ResourceManager.GetString("GenderO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App language.
        /// </summary>
        internal static string GENSET_lbl1 {
            get {
                return ResourceManager.GetString("GENSET-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Virtual keyboard in full screen.
        /// </summary>
        internal static string GENSET_lbl12 {
            get {
                return ResourceManager.GetString("GENSET-lbl12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App theme.
        /// </summary>
        internal static string GENSET_lbl2 {
            get {
                return ResourceManager.GetString("GENSET-lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App currency.
        /// </summary>
        internal static string GENSET_lbl3 {
            get {
                return ResourceManager.GetString("GENSET-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable individual discount button.
        /// </summary>
        internal static string GENSET_lbl4 {
            get {
                return ResourceManager.GetString("GENSET-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable scrollbars.
        /// </summary>
        internal static string GENSET_lbl5 {
            get {
                return ResourceManager.GetString("GENSET-lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recipe page in read only mode.
        /// </summary>
        internal static string GENSET_lbl6 {
            get {
                return ResourceManager.GetString("GENSET-lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate &quot;Headquarter&quot; mode.
        /// </summary>
        internal static string GENSET_lbl7 {
            get {
                return ResourceManager.GetString("GENSET-lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à apply only for &quot;Light&quot; theme.
        /// </summary>
        internal static string GENSET_lbl8 {
            get {
                return ResourceManager.GetString("GENSET-lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Manager mode.
        /// </summary>
        internal static string GENSET_lbl9 {
            get {
                return ResourceManager.GetString("GENSET-lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        internal static string Getimage {
            get {
                return ResourceManager.GetString("Getimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à g.
        /// </summary>
        internal static string Gramm {
            get {
                return ResourceManager.GetString("Gramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à h.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your email.
        /// </summary>
        internal static string iFPP_lbl1 {
            get {
                return ResourceManager.GetString("iFPP-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter confirmation code.
        /// </summary>
        internal static string iFPP_lbl2 {
            get {
                return ResourceManager.GetString("iFPP-lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember the pass?.
        /// </summary>
        internal static string iFPP_lbl3 {
            get {
                return ResourceManager.GetString("iFPP-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use password.
        /// </summary>
        internal static string iFPP_lbl4 {
            get {
                return ResourceManager.GetString("iFPP-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discount amount %.
        /// </summary>
        internal static string IndivDisc_lbl2 {
            get {
                return ResourceManager.GetString("IndivDisc-lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of discounted dishes.
        /// </summary>
        internal static string IndivDisc_lbl3 {
            get {
                return ResourceManager.GetString("IndivDisc-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Occurrences.
        /// </summary>
        internal static string IndivDisc_lbl4 {
            get {
                return ResourceManager.GetString("IndivDisc-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ↑ Double click to select.
        /// </summary>
        internal static string IndivDisc_lbl5 {
            get {
                return ResourceManager.GetString("IndivDisc-lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert.
        /// </summary>
        internal static string Inserer {
            get {
                return ResourceManager.GetString("Inserer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data inserted and saved successfully.
        /// </summary>
        internal static string Insertsucess {
            get {
                return ResourceManager.GetString("Insertsucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Email address.
        /// </summary>
        internal static string Inv_Email {
            get {
                return ResourceManager.GetString("Inv-Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid TypeID. Must be an integer.
        /// </summary>
        internal static string InvalidFoodID {
            get {
                return ResourceManager.GetString("InvalidFoodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Price format.
        /// </summary>
        internal static string Invalidprice {
            get {
                return ResourceManager.GetString("Invalidprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show password.
        /// </summary>
        internal static string LGN_chbox1 {
            get {
                return ResourceManager.GetString("LGN-chbox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string LGN_lbl1 {
            get {
                return ResourceManager.GetString("LGN-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string LGN_lbl2 {
            get {
                return ResourceManager.GetString("LGN-lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot your Password?.
        /// </summary>
        internal static string LGN_lbl3 {
            get {
                return ResourceManager.GetString("LGN-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click here.
        /// </summary>
        internal static string LGN_lbl4 {
            get {
                return ResourceManager.GetString("LGN-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moderate password.
        /// </summary>
        internal static string M_password {
            get {
                return ResourceManager.GetString("M-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an account.
        /// </summary>
        internal static string Makeaccount {
            get {
                return ResourceManager.GetString("Makeaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order builder.
        /// </summary>
        internal static string MF_btn1 {
            get {
                return ResourceManager.GetString("MF-btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dish restriction.
        /// </summary>
        internal static string MF_btn10 {
            get {
                return ResourceManager.GetString("MF-btn10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string MF_btn11 {
            get {
                return ResourceManager.GetString("MF-btn11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personnel.
        /// </summary>
        internal static string MF_btn13 {
            get {
                return ResourceManager.GetString("MF-btn13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timetable.
        /// </summary>
        internal static string MF_btn14 {
            get {
                return ResourceManager.GetString("MF-btn14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departments.
        /// </summary>
        internal static string MF_btn15 {
            get {
                return ResourceManager.GetString("MF-btn15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery.
        /// </summary>
        internal static string MF_btn16 {
            get {
                return ResourceManager.GetString("MF-btn16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory.
        /// </summary>
        internal static string MF_btn17 {
            get {
                return ResourceManager.GetString("MF-btn17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loyalty program.
        /// </summary>
        internal static string MF_btn18 {
            get {
                return ResourceManager.GetString("MF-btn18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other data.
        /// </summary>
        internal static string MF_btn19 {
            get {
                return ResourceManager.GetString("MF-btn19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily reports.
        /// </summary>
        internal static string MF_btn2 {
            get {
                return ResourceManager.GetString("MF-btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dish data.
        /// </summary>
        internal static string MF_btn3 {
            get {
                return ResourceManager.GetString("MF-btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recipe constructor.
        /// </summary>
        internal static string MF_btn4 {
            get {
                return ResourceManager.GetString("MF-btn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit orders.
        /// </summary>
        internal static string MF_btn5 {
            get {
                return ResourceManager.GetString("MF-btn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close shift.
        /// </summary>
        internal static string MF_btn6 {
            get {
                return ResourceManager.GetString("MF-btn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily charts.
        /// </summary>
        internal static string MF_btn7 {
            get {
                return ResourceManager.GetString("MF-btn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Daily spendings.
        /// </summary>
        internal static string MF_btn8 {
            get {
                return ResourceManager.GetString("MF-btn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table reservation.
        /// </summary>
        internal static string MF_btn9 {
            get {
                return ResourceManager.GetString("MF-btn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit app.
        /// </summary>
        internal static string MF_ctxtMenuQuit {
            get {
                return ResourceManager.GetString("MF-ctxtMenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display .
        /// </summary>
        internal static string MF_ctxtMenuShow {
            get {
                return ResourceManager.GetString("MF-ctxtMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Departments.
        /// </summary>
        internal static string MF_label1 {
            get {
                return ResourceManager.GetString("MF-label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shift.
        /// </summary>
        internal static string MF_label2 {
            get {
                return ResourceManager.GetString("MF-label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order.
        /// </summary>
        internal static string MF_label3 {
            get {
                return ResourceManager.GetString("MF-label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Staff and products.
        /// </summary>
        internal static string MF_label4 {
            get {
                return ResourceManager.GetString("MF-label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Managers.
        /// </summary>
        internal static string MF_label5 {
            get {
                return ResourceManager.GetString("MF-label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Services.
        /// </summary>
        internal static string MF_label6 {
            get {
                return ResourceManager.GetString("MF-label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login as manager.
        /// </summary>
        internal static string MF_linklbl1 {
            get {
                return ResourceManager.GetString("MF-linklbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit manager mode.
        /// </summary>
        internal static string MF_linklbl2 {
            get {
                return ResourceManager.GetString("MF-linklbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à      New price:.
        /// </summary>
        internal static string Newprice {
            get {
                return ResourceManager.GetString("Newprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No premium account.
        /// </summary>
        internal static string Noaccount {
            get {
                return ResourceManager.GetString("Noaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No account to delete.
        /// </summary>
        internal static string Noaccountdel {
            get {
                return ResourceManager.GetString("Noaccountdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string Nobutton {
            get {
                return ResourceManager.GetString("Nobutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No internet connection.
        /// </summary>
        internal static string Nointernet {
            get {
                return ResourceManager.GetString("Nointernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing data in some or all required columns(4 first)..
        /// </summary>
        internal static string Notenoughdata {
            get {
                return ResourceManager.GetString("Notenoughdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No value.
        /// </summary>
        internal static string Novalue {
            get {
                return ResourceManager.GetString("Novalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse.
        /// </summary>
        internal static string Parcourir {
            get {
                return ResourceManager.GetString("Parcourir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay using.
        /// </summary>
        internal static string Popdefaultpay {
            get {
                return ResourceManager.GetString("Popdefaultpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected dish?.
        /// </summary>
        internal static string Popdeletedish {
            get {
                return ResourceManager.GetString("Popdeletedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delivery type.
        /// </summary>
        internal static string Printdelivery {
            get {
                return ResourceManager.GetString("Printdelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guest contact:.
        /// </summary>
        internal static string Printtableguestcontact {
            get {
                return ResourceManager.GetString("Printtableguestcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guest gender:.
        /// </summary>
        internal static string Printtableguestgender {
            get {
                return ResourceManager.GetString("Printtableguestgender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Guest name:.
        /// </summary>
        internal static string Printtableguestname {
            get {
                return ResourceManager.GetString("Printtableguestname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of guests:.
        /// </summary>
        internal static string Printtableguests {
            get {
                return ResourceManager.GetString("Printtableguests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table number:.
        /// </summary>
        internal static string Printtablenumber {
            get {
                return ResourceManager.GetString("Printtablenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status:.
        /// </summary>
        internal static string Printtablestatus {
            get {
                return ResourceManager.GetString("Printtablestatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you for your reservation!.
        /// </summary>
        internal static string Printtablethanks {
            get {
                return ResourceManager.GetString("Printtablethanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reservation time:.
        /// </summary>
        internal static string Printtabletime {
            get {
                return ResourceManager.GetString("Printtabletime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mobile application for managers coming soon!.
        /// </summary>
        internal static string QRCode_Msg {
            get {
                return ResourceManager.GetString("QRCode-Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client:.
        /// </summary>
        internal static string Receiptprintclient {
            get {
                return ResourceManager.GetString("Receiptprintclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currency:.
        /// </summary>
        internal static string Receiptprintcurrency {
            get {
                return ResourceManager.GetString("Receiptprintcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment method:.
        /// </summary>
        internal static string Receiptprintpaymethod {
            get {
                return ResourceManager.GetString("Receiptprintpaymethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Functionality coming soon!.
        /// </summary>
        internal static string Receiptprintqrcode {
            get {
                return ResourceManager.GetString("Receiptprintqrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subtotal.
        /// </summary>
        internal static string Receiptprintsubtotal {
            get {
                return ResourceManager.GetString("Receiptprintsubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table.
        /// </summary>
        internal static string Receiptprinttable {
            get {
                return ResourceManager.GetString("Receiptprinttable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à THANKS FOR YOUR PURCHASE!.
        /// </summary>
        internal static string Receiptprintthanks {
            get {
                return ResourceManager.GetString("Receiptprintthanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total:.
        /// </summary>
        internal static string Receiptprinttotal {
            get {
                return ResourceManager.GetString("Receiptprinttotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is a copy and may have been modified!.
        /// </summary>
        internal static string Receiptprintwarning {
            get {
                return ResourceManager.GetString("Receiptprintwarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reservations.
        /// </summary>
        internal static string RF_btn1 {
            get {
                return ResourceManager.GetString("RF-btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tables plan.
        /// </summary>
        internal static string RF_btn3 {
            get {
                return ResourceManager.GetString("RF-btn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No reservation at the moment.
        /// </summary>
        internal static string RF_lbl1 {
            get {
                return ResourceManager.GetString("RF-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All rows deleted successfully.
        /// </summary>
        internal static string Rowsdeleted {
            get {
                return ResourceManager.GetString("Rowsdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No rows were deleted.
        /// </summary>
        internal static string Rowsnotdeleted {
            get {
                return ResourceManager.GetString("Rowsnotdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an Image.
        /// </summary>
        internal static string Sel_image {
            get {
                return ResourceManager.GetString("Sel-image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hardware.
        /// </summary>
        internal static string SET_btn1 {
            get {
                return ResourceManager.GetString("SET-btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account.
        /// </summary>
        internal static string SET_btn2 {
            get {
                return ResourceManager.GetString("SET-btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General .
        /// </summary>
        internal static string SET_btn6 {
            get {
                return ResourceManager.GetString("SET-btn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subscription.
        /// </summary>
        internal static string SET_rbtn1 {
            get {
                return ResourceManager.GetString("SET-rbtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save choice.
        /// </summary>
        internal static string SETACC_btn2 {
            get {
                return ResourceManager.GetString("SETACC-btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apply changes.
        /// </summary>
        internal static string SETACC_btnsACH {
            get {
                return ResourceManager.GetString("SETACC-btnsACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location name.
        /// </summary>
        internal static string SETACC_lbl1 {
            get {
                return ResourceManager.GetString("SETACC-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan to connect to mobile app.
        /// </summary>
        internal static string SETACC_lbl10 {
            get {
                return ResourceManager.GetString("SETACC-lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MODIFY YOUR DATA.
        /// </summary>
        internal static string SETACC_lbl3 {
            get {
                return ResourceManager.GetString("SETACC-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify the location.
        /// </summary>
        internal static string SETACC_lbl5 {
            get {
                return ResourceManager.GetString("SETACC-lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location address.
        /// </summary>
        internal static string SETACC_lbl6 {
            get {
                return ResourceManager.GetString("SETACC-lbl6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business name.
        /// </summary>
        internal static string SETACC_lbl7 {
            get {
                return ResourceManager.GetString("SETACC-lbl7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email address.
        /// </summary>
        internal static string SETACC_lbl8 {
            get {
                return ResourceManager.GetString("SETACC-lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string SETACC_lbl9 {
            get {
                return ResourceManager.GetString("SETACC-lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Locations.
        /// </summary>
        internal static string SETACC_rbtn1 {
            get {
                return ResourceManager.GetString("SETACC-rbtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save image.
        /// </summary>
        internal static string SETACC_rbtn6 {
            get {
                return ResourceManager.GetString("SETACC-rbtn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete image.
        /// </summary>
        internal static string SETACC_rbtn7 {
            get {
                return ResourceManager.GetString("SETACC-rbtn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm email.
        /// </summary>
        internal static string SETACC_rbtn8 {
            get {
                return ResourceManager.GetString("SETACC-rbtn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print settings.
        /// </summary>
        internal static string SETPRINT_lbl1 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print restaurant logo if any.
        /// </summary>
        internal static string SETPRINT_lbl10 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print Receipt QR code.
        /// </summary>
        internal static string SETPRINT_lbl11 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of copies per print.
        /// </summary>
        internal static string SETPRINT_lbl2 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print to new line at &quot;+&quot; in dish name.
        /// </summary>
        internal static string SETPRINT_lbl5 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automatic receipts print.
        /// </summary>
        internal static string SETPRINT_lbl8 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print to new line if necessary.
        /// </summary>
        internal static string SETPRINT_lbl9 {
            get {
                return ResourceManager.GetString("SETPRINT-lbl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sheets.
        /// </summary>
        internal static string Sheets {
            get {
                return ResourceManager.GetString("Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skip all.
        /// </summary>
        internal static string Skipall {
            get {
                return ResourceManager.GetString("Skipall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Amounts(g).
        /// </summary>
        internal static string SREC_Amounting {
            get {
                return ResourceManager.GetString("SREC-Amounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Used in:.
        /// </summary>
        internal static string SREC_Indishes {
            get {
                return ResourceManager.GetString("SREC-Indishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print recipe.
        /// </summary>
        internal static string SREC_lbl4 {
            get {
                return ResourceManager.GetString("SREC-lbl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Products used.
        /// </summary>
        internal static string SREC_Prodname {
            get {
                return ResourceManager.GetString("SREC-Prodname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Products.
        /// </summary>
        internal static string SREC_rbtn6 {
            get {
                return ResourceManager.GetString("SREC-rbtn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recipes.
        /// </summary>
        internal static string SREC_rbtn7 {
            get {
                return ResourceManager.GetString("SREC-rbtn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Receipts.
        /// </summary>
        internal static string Staffdash_lbl1 {
            get {
                return ResourceManager.GetString("Staffdash-lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Days with us.
        /// </summary>
        internal static string Staffdash_lbl3 {
            get {
                return ResourceManager.GetString("Staffdash-lbl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In revenus.
        /// </summary>
        internal static string Staffdash_lbl5 {
            get {
                return ResourceManager.GetString("Staffdash-lbl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session opened the .
        /// </summary>
        internal static string Staffdash01 {
            get {
                return ResourceManager.GetString("Staffdash01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at: .
        /// </summary>
        internal static string Staffdash02 {
            get {
                return ResourceManager.GetString("Staffdash02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à      Discount amount:.
        /// </summary>
        internal static string Sumdiscount {
            get {
                return ResourceManager.GetString("Sumdiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancelled.
        /// </summary>
        internal static string Tablecancelled {
            get {
                return ResourceManager.GetString("Tablecancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Completed.
        /// </summary>
        internal static string Tablecompleted {
            get {
                return ResourceManager.GetString("Tablecompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No status .
        /// </summary>
        internal static string Tablenostatus {
            get {
                return ResourceManager.GetString("Tablenostatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seat.
        /// </summary>
        internal static string TBS_Place {
            get {
                return ResourceManager.GetString("TBS-Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seats.
        /// </summary>
        internal static string TBS_Places {
            get {
                return ResourceManager.GetString("TBS-Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tables.
        /// </summary>
        internal static string TR_rbtn1 {
            get {
                return ResourceManager.GetString("TR-rbtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unexpected error occurred..
        /// </summary>
        internal static string Unexpectederror {
            get {
                return ResourceManager.GetString("Unexpectederror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weak password.
        /// </summary>
        internal static string W_password {
            get {
                return ResourceManager.GetString("W-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yesbutton {
            get {
                return ResourceManager.GetString("Yesbutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        internal static string место {
            get {
                return ResourceManager.GetString("место", resourceCulture);
            }
        }
    }
}
